  cassandra1:
    image: cassandra:4.1
    container_name: cassandra1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=healthcare-cluster
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_LISTEN_ADDRESS=auto
      - CASSANDRA_BROADCAST_ADDRESS=cassandra1
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_BROADCAST_RPC_ADDRESS=cassandra1
    volumes:
      - ./cassandra1_data:/var/lib/cassandra
    networks:
      cassandra_net:
        aliases:
          - cassandra1

  cassandra2:
    image: cassandra:4.1
    container_name: cassandra2
    depends_on:
      - cassandra1
    environment:
      - CASSANDRA_CLUSTER_NAME=healthcare-cluster
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_LISTEN_ADDRESS=auto
      - CASSANDRA_BROADCAST_ADDRESS=cassandra2
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_BROADCAST_RPC_ADDRESS=cassandra2
    volumes:
      - ./cassandra2_data:/var/lib/cassandra
    networks:
      cassandra_net:
        aliases:
          - cassandra2
